packages:
  - "apps/web"
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: 4.1.9
  vite-plus: latest
overrides:
  vite: "catalog:"
  vitest: "catalog:"
  drizzle-orm: 0.45.2
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
