/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardLayoutRouteImport } from './routes/_dashboard/layout'
import { Route as AuthLayoutRouteImport } from './routes/auth/layout'
import { Route as IconRouteImport } from './routes/icon'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as DashboardAdminIndexRouteImport } from './routes/_dashboard/admin/index'
import { Route as DashboardManagerIndexRouteImport } from './routes/_dashboard/manager/index'
import { Route as DashboardStaffIndexRouteImport } from './routes/_dashboard/staff/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardAdminAdminsIndexRouteImport } from './routes/_dashboard/admin/admins/index'
import { Route as DashboardAdminLocationsIndexRouteImport } from './routes/_dashboard/admin/locations/index'
import { Route as DashboardAdminManagersIndexRouteImport } from './routes/_dashboard/admin/managers/index'
import { Route as DashboardAdminSchedulesIndexRouteImport } from './routes/_dashboard/admin/schedules/index'
import { Route as DashboardAdminStaffIndexRouteImport } from './routes/_dashboard/admin/staff/index'
import { Route as DashboardManagerLocationsIndexRouteImport } from './routes/_dashboard/manager/locations/index'
import { Route as DashboardManagerScheduleIndexRouteImport } from './routes/_dashboard/manager/schedule/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IconRoute = IconRouteImport.update({
  id: '/icon',
  path: '/icon',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardManagerIndexRoute = DashboardManagerIndexRouteImport.update({
  id: '/manager/',
  path: '/manager/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardStaffIndexRoute = DashboardStaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminAdminsIndexRoute =
  DashboardAdminAdminsIndexRouteImport.update({
    id: '/admin/admins/',
    path: '/admin/admins/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardAdminLocationsIndexRoute =
  DashboardAdminLocationsIndexRouteImport.update({
    id: '/admin/locations/',
    path: '/admin/locations/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardAdminManagersIndexRoute =
  DashboardAdminManagersIndexRouteImport.update({
    id: '/admin/managers/',
    path: '/admin/managers/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardAdminSchedulesIndexRoute =
  DashboardAdminSchedulesIndexRouteImport.update({
    id: '/admin/schedules/',
    path: '/admin/schedules/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardAdminStaffIndexRoute =
  DashboardAdminStaffIndexRouteImport.update({
    id: '/admin/staff/',
    path: '/admin/staff/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardManagerLocationsIndexRoute =
  DashboardManagerLocationsIndexRouteImport.update({
    id: '/manager/locations/',
    path: '/manager/locations/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardManagerScheduleIndexRoute =
  DashboardManagerScheduleIndexRouteImport.update({
    id: '/manager/schedule/',
    path: '/manager/schedule/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthLayoutRouteWithChildren
  '/icon': typeof IconRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/': typeof AuthIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/': typeof DashboardAdminIndexRoute
  '/manager/': typeof DashboardManagerIndexRoute
  '/staff/': typeof DashboardStaffIndexRoute
  '/admin/admins/': typeof DashboardAdminAdminsIndexRoute
  '/admin/locations/': typeof DashboardAdminLocationsIndexRoute
  '/admin/managers/': typeof DashboardAdminManagersIndexRoute
  '/admin/schedules/': typeof DashboardAdminSchedulesIndexRoute
  '/admin/staff/': typeof DashboardAdminStaffIndexRoute
  '/manager/locations/': typeof DashboardManagerLocationsIndexRoute
  '/manager/schedule/': typeof DashboardManagerScheduleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/icon': typeof IconRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth': typeof AuthIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin': typeof DashboardAdminIndexRoute
  '/manager': typeof DashboardManagerIndexRoute
  '/staff': typeof DashboardStaffIndexRoute
  '/admin/admins': typeof DashboardAdminAdminsIndexRoute
  '/admin/locations': typeof DashboardAdminLocationsIndexRoute
  '/admin/managers': typeof DashboardAdminManagersIndexRoute
  '/admin/schedules': typeof DashboardAdminSchedulesIndexRoute
  '/admin/staff': typeof DashboardAdminStaffIndexRoute
  '/manager/locations': typeof DashboardManagerLocationsIndexRoute
  '/manager/schedule': typeof DashboardManagerScheduleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardLayoutRouteWithChildren
  '/auth': typeof AuthLayoutRouteWithChildren
  '/icon': typeof IconRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/': typeof AuthIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_dashboard/admin/': typeof DashboardAdminIndexRoute
  '/_dashboard/manager/': typeof DashboardManagerIndexRoute
  '/_dashboard/staff/': typeof DashboardStaffIndexRoute
  '/_dashboard/admin/admins/': typeof DashboardAdminAdminsIndexRoute
  '/_dashboard/admin/locations/': typeof DashboardAdminLocationsIndexRoute
  '/_dashboard/admin/managers/': typeof DashboardAdminManagersIndexRoute
  '/_dashboard/admin/schedules/': typeof DashboardAdminSchedulesIndexRoute
  '/_dashboard/admin/staff/': typeof DashboardAdminStaffIndexRoute
  '/_dashboard/manager/locations/': typeof DashboardManagerLocationsIndexRoute
  '/_dashboard/manager/schedule/': typeof DashboardManagerScheduleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/icon'
    | '/privacy'
    | '/terms'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/auth/'
    | '/api/auth/$'
    | '/admin/'
    | '/manager/'
    | '/staff/'
    | '/admin/admins/'
    | '/admin/locations/'
    | '/admin/managers/'
    | '/admin/schedules/'
    | '/admin/staff/'
    | '/manager/locations/'
    | '/manager/schedule/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/icon'
    | '/privacy'
    | '/terms'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/auth'
    | '/api/auth/$'
    | '/admin'
    | '/manager'
    | '/staff'
    | '/admin/admins'
    | '/admin/locations'
    | '/admin/managers'
    | '/admin/schedules'
    | '/admin/staff'
    | '/manager/locations'
    | '/manager/schedule'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/auth'
    | '/icon'
    | '/privacy'
    | '/terms'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/auth/'
    | '/api/auth/$'
    | '/_dashboard/admin/'
    | '/_dashboard/manager/'
    | '/_dashboard/staff/'
    | '/_dashboard/admin/admins/'
    | '/_dashboard/admin/locations/'
    | '/_dashboard/admin/managers/'
    | '/_dashboard/admin/schedules/'
    | '/_dashboard/admin/staff/'
    | '/_dashboard/manager/locations/'
    | '/_dashboard/manager/schedule/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  IconRoute: typeof IconRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/icon': {
      id: '/icon'
      path: '/icon'
      fullPath: '/icon'
      preLoaderRoute: typeof IconRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_dashboard/admin/': {
      id: '/_dashboard/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/manager/': {
      id: '/_dashboard/manager/'
      path: '/manager'
      fullPath: '/manager/'
      preLoaderRoute: typeof DashboardManagerIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/staff/': {
      id: '/_dashboard/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof DashboardStaffIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/admin/admins/': {
      id: '/_dashboard/admin/admins/'
      path: '/admin/admins'
      fullPath: '/admin/admins/'
      preLoaderRoute: typeof DashboardAdminAdminsIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/admin/locations/': {
      id: '/_dashboard/admin/locations/'
      path: '/admin/locations'
      fullPath: '/admin/locations/'
      preLoaderRoute: typeof DashboardAdminLocationsIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/admin/managers/': {
      id: '/_dashboard/admin/managers/'
      path: '/admin/managers'
      fullPath: '/admin/managers/'
      preLoaderRoute: typeof DashboardAdminManagersIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/admin/schedules/': {
      id: '/_dashboard/admin/schedules/'
      path: '/admin/schedules'
      fullPath: '/admin/schedules/'
      preLoaderRoute: typeof DashboardAdminSchedulesIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/admin/staff/': {
      id: '/_dashboard/admin/staff/'
      path: '/admin/staff'
      fullPath: '/admin/staff/'
      preLoaderRoute: typeof DashboardAdminStaffIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/manager/locations/': {
      id: '/_dashboard/manager/locations/'
      path: '/manager/locations'
      fullPath: '/manager/locations/'
      preLoaderRoute: typeof DashboardManagerLocationsIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/manager/schedule/': {
      id: '/_dashboard/manager/schedule/'
      path: '/manager/schedule'
      fullPath: '/manager/schedule/'
      preLoaderRoute: typeof DashboardManagerScheduleIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
  }
}

interface DashboardLayoutRouteChildren {
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
  DashboardManagerIndexRoute: typeof DashboardManagerIndexRoute
  DashboardStaffIndexRoute: typeof DashboardStaffIndexRoute
  DashboardAdminAdminsIndexRoute: typeof DashboardAdminAdminsIndexRoute
  DashboardAdminLocationsIndexRoute: typeof DashboardAdminLocationsIndexRoute
  DashboardAdminManagersIndexRoute: typeof DashboardAdminManagersIndexRoute
  DashboardAdminSchedulesIndexRoute: typeof DashboardAdminSchedulesIndexRoute
  DashboardAdminStaffIndexRoute: typeof DashboardAdminStaffIndexRoute
  DashboardManagerLocationsIndexRoute: typeof DashboardManagerLocationsIndexRoute
  DashboardManagerScheduleIndexRoute: typeof DashboardManagerScheduleIndexRoute
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
  DashboardManagerIndexRoute: DashboardManagerIndexRoute,
  DashboardStaffIndexRoute: DashboardStaffIndexRoute,
  DashboardAdminAdminsIndexRoute: DashboardAdminAdminsIndexRoute,
  DashboardAdminLocationsIndexRoute: DashboardAdminLocationsIndexRoute,
  DashboardAdminManagersIndexRoute: DashboardAdminManagersIndexRoute,
  DashboardAdminSchedulesIndexRoute: DashboardAdminSchedulesIndexRoute,
  DashboardAdminStaffIndexRoute: DashboardAdminStaffIndexRoute,
  DashboardManagerLocationsIndexRoute: DashboardManagerLocationsIndexRoute,
  DashboardManagerScheduleIndexRoute: DashboardManagerScheduleIndexRoute,
}

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
)

interface AuthLayoutRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  IconRoute: IconRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
