/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardLayoutRouteImport } from './routes/_dashboard/layout'
import { Route as AuthLayoutRouteImport } from './routes/auth/layout'
import { Route as IconRouteImport } from './routes/icon'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as DashboardAdminIndexRouteImport } from './routes/_dashboard/admin/index'
import { Route as DashboardAdminSchedulesRouteImport } from './routes/_dashboard/admin/schedules'
import { Route as DashboardManagerIndexRouteImport } from './routes/_dashboard/manager/index'
import { Route as DashboardStaffIndexRouteImport } from './routes/_dashboard/staff/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardAdminAdminsIndexRouteImport } from './routes/_dashboard/admin/admins/index'
import { Route as DashboardAdminAuditIndexRouteImport } from './routes/_dashboard/admin/audit/index'
import { Route as DashboardAdminLocationsIndexRouteImport } from './routes/_dashboard/admin/locations/index'
import { Route as DashboardAdminManagersIndexRouteImport } from './routes/_dashboard/admin/managers/index'
import { Route as DashboardAdminManagersManagerIdRouteImport } from './routes/_dashboard/admin/managers/$managerId'
import { Route as DashboardAdminSchedulesIndexRouteImport } from './routes/_dashboard/admin/schedules/index'
import { Route as DashboardAdminSchedulesOnDutyRouteImport } from './routes/_dashboard/admin/schedules/on-duty'
import { Route as DashboardAdminSchedulesWhoRouteImport } from './routes/_dashboard/admin/schedules/who'
import { Route as DashboardAdminStaffIndexRouteImport } from './routes/_dashboard/admin/staff/index'
import { Route as DashboardAdminStaffStaffIdRouteImport } from './routes/_dashboard/admin/staff/$staffId'
import { Route as DashboardManagerLocationsIndexRouteImport } from './routes/_dashboard/manager/locations/index'
import { Route as DashboardManagerRequestsIndexRouteImport } from './routes/_dashboard/manager/requests/index'
import { Route as DashboardManagerScheduleIndexRouteImport } from './routes/_dashboard/manager/schedule/index'
import { Route as DashboardManagerTeamIndexRouteImport } from './routes/_dashboard/manager/team/index'
import { Route as DashboardManagerTeamStaffIdRouteImport } from './routes/_dashboard/manager/team/$staffId'
import { Route as DashboardStaffCoverageIndexRouteImport } from './routes/_dashboard/staff/coverage/index'
import { Route as DashboardStaffNotificationsIndexRouteImport } from './routes/_dashboard/staff/notifications/index'
import { Route as DashboardManagerScheduleLocationIdIndexRouteImport } from './routes/_dashboard/manager/schedule/$locationId/index'
import { Route as DashboardManagerScheduleLocationIdWeekStartRouteImport } from './routes/_dashboard/manager/schedule/$locationId/$weekStart'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IconRoute = IconRouteImport.update({
  id: '/icon',
  path: '/icon',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardAdminSchedulesRoute = DashboardAdminSchedulesRouteImport.update({
  id: '/admin/schedules',
  path: '/admin/schedules',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardManagerIndexRoute = DashboardManagerIndexRouteImport.update({
  id: '/manager/',
  path: '/manager/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardStaffIndexRoute = DashboardStaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminAdminsIndexRoute =
  DashboardAdminAdminsIndexRouteImport.update({
    id: '/admin/admins/',
    path: '/admin/admins/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardAdminAuditIndexRoute =
  DashboardAdminAuditIndexRouteImport.update({
    id: '/admin/audit/',
    path: '/admin/audit/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardAdminLocationsIndexRoute =
  DashboardAdminLocationsIndexRouteImport.update({
    id: '/admin/locations/',
    path: '/admin/locations/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardAdminManagersIndexRoute =
  DashboardAdminManagersIndexRouteImport.update({
    id: '/admin/managers/',
    path: '/admin/managers/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardAdminManagersManagerIdRoute =
  DashboardAdminManagersManagerIdRouteImport.update({
    id: '/admin/managers/$managerId',
    path: '/admin/managers/$managerId',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardAdminSchedulesIndexRoute =
  DashboardAdminSchedulesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardAdminSchedulesRoute,
  } as any)
const DashboardAdminSchedulesOnDutyRoute =
  DashboardAdminSchedulesOnDutyRouteImport.update({
    id: '/on-duty',
    path: '/on-duty',
    getParentRoute: () => DashboardAdminSchedulesRoute,
  } as any)
const DashboardAdminSchedulesWhoRoute =
  DashboardAdminSchedulesWhoRouteImport.update({
    id: '/who',
    path: '/who',
    getParentRoute: () => DashboardAdminSchedulesRoute,
  } as any)
const DashboardAdminStaffIndexRoute =
  DashboardAdminStaffIndexRouteImport.update({
    id: '/admin/staff/',
    path: '/admin/staff/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardAdminStaffStaffIdRoute =
  DashboardAdminStaffStaffIdRouteImport.update({
    id: '/admin/staff/$staffId',
    path: '/admin/staff/$staffId',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardManagerLocationsIndexRoute =
  DashboardManagerLocationsIndexRouteImport.update({
    id: '/manager/locations/',
    path: '/manager/locations/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardManagerRequestsIndexRoute =
  DashboardManagerRequestsIndexRouteImport.update({
    id: '/manager/requests/',
    path: '/manager/requests/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardManagerScheduleIndexRoute =
  DashboardManagerScheduleIndexRouteImport.update({
    id: '/manager/schedule/',
    path: '/manager/schedule/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardManagerTeamIndexRoute =
  DashboardManagerTeamIndexRouteImport.update({
    id: '/manager/team/',
    path: '/manager/team/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardManagerTeamStaffIdRoute =
  DashboardManagerTeamStaffIdRouteImport.update({
    id: '/manager/team/$staffId',
    path: '/manager/team/$staffId',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardStaffCoverageIndexRoute =
  DashboardStaffCoverageIndexRouteImport.update({
    id: '/staff/coverage/',
    path: '/staff/coverage/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardStaffNotificationsIndexRoute =
  DashboardStaffNotificationsIndexRouteImport.update({
    id: '/staff/notifications/',
    path: '/staff/notifications/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardManagerScheduleLocationIdIndexRoute =
  DashboardManagerScheduleLocationIdIndexRouteImport.update({
    id: '/manager/schedule/$locationId/',
    path: '/manager/schedule/$locationId/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardManagerScheduleLocationIdWeekStartRoute =
  DashboardManagerScheduleLocationIdWeekStartRouteImport.update({
    id: '/manager/schedule/$locationId/$weekStart',
    path: '/manager/schedule/$locationId/$weekStart',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthLayoutRouteWithChildren
  '/icon': typeof IconRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/': typeof AuthIndexRoute
  '/admin/schedules': typeof DashboardAdminSchedulesRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/': typeof DashboardAdminIndexRoute
  '/manager/': typeof DashboardManagerIndexRoute
  '/staff/': typeof DashboardStaffIndexRoute
  '/admin/managers/$managerId': typeof DashboardAdminManagersManagerIdRoute
  '/admin/schedules/on-duty': typeof DashboardAdminSchedulesOnDutyRoute
  '/admin/schedules/who': typeof DashboardAdminSchedulesWhoRoute
  '/admin/staff/$staffId': typeof DashboardAdminStaffStaffIdRoute
  '/manager/team/$staffId': typeof DashboardManagerTeamStaffIdRoute
  '/admin/admins/': typeof DashboardAdminAdminsIndexRoute
  '/admin/audit/': typeof DashboardAdminAuditIndexRoute
  '/admin/locations/': typeof DashboardAdminLocationsIndexRoute
  '/admin/managers/': typeof DashboardAdminManagersIndexRoute
  '/admin/schedules/': typeof DashboardAdminSchedulesIndexRoute
  '/admin/staff/': typeof DashboardAdminStaffIndexRoute
  '/manager/locations/': typeof DashboardManagerLocationsIndexRoute
  '/manager/requests/': typeof DashboardManagerRequestsIndexRoute
  '/manager/schedule/': typeof DashboardManagerScheduleIndexRoute
  '/manager/team/': typeof DashboardManagerTeamIndexRoute
  '/staff/coverage/': typeof DashboardStaffCoverageIndexRoute
  '/staff/notifications/': typeof DashboardStaffNotificationsIndexRoute
  '/manager/schedule/$locationId/$weekStart': typeof DashboardManagerScheduleLocationIdWeekStartRoute
  '/manager/schedule/$locationId/': typeof DashboardManagerScheduleLocationIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/icon': typeof IconRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth': typeof AuthIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin': typeof DashboardAdminIndexRoute
  '/manager': typeof DashboardManagerIndexRoute
  '/staff': typeof DashboardStaffIndexRoute
  '/admin/managers/$managerId': typeof DashboardAdminManagersManagerIdRoute
  '/admin/schedules/on-duty': typeof DashboardAdminSchedulesOnDutyRoute
  '/admin/schedules/who': typeof DashboardAdminSchedulesWhoRoute
  '/admin/staff/$staffId': typeof DashboardAdminStaffStaffIdRoute
  '/manager/team/$staffId': typeof DashboardManagerTeamStaffIdRoute
  '/admin/admins': typeof DashboardAdminAdminsIndexRoute
  '/admin/audit': typeof DashboardAdminAuditIndexRoute
  '/admin/locations': typeof DashboardAdminLocationsIndexRoute
  '/admin/managers': typeof DashboardAdminManagersIndexRoute
  '/admin/schedules': typeof DashboardAdminSchedulesIndexRoute
  '/admin/staff': typeof DashboardAdminStaffIndexRoute
  '/manager/locations': typeof DashboardManagerLocationsIndexRoute
  '/manager/requests': typeof DashboardManagerRequestsIndexRoute
  '/manager/schedule': typeof DashboardManagerScheduleIndexRoute
  '/manager/team': typeof DashboardManagerTeamIndexRoute
  '/staff/coverage': typeof DashboardStaffCoverageIndexRoute
  '/staff/notifications': typeof DashboardStaffNotificationsIndexRoute
  '/manager/schedule/$locationId/$weekStart': typeof DashboardManagerScheduleLocationIdWeekStartRoute
  '/manager/schedule/$locationId': typeof DashboardManagerScheduleLocationIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardLayoutRouteWithChildren
  '/auth': typeof AuthLayoutRouteWithChildren
  '/icon': typeof IconRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/': typeof AuthIndexRoute
  '/_dashboard/admin/schedules': typeof DashboardAdminSchedulesRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_dashboard/admin/': typeof DashboardAdminIndexRoute
  '/_dashboard/manager/': typeof DashboardManagerIndexRoute
  '/_dashboard/staff/': typeof DashboardStaffIndexRoute
  '/_dashboard/admin/managers/$managerId': typeof DashboardAdminManagersManagerIdRoute
  '/_dashboard/admin/schedules/on-duty': typeof DashboardAdminSchedulesOnDutyRoute
  '/_dashboard/admin/schedules/who': typeof DashboardAdminSchedulesWhoRoute
  '/_dashboard/admin/staff/$staffId': typeof DashboardAdminStaffStaffIdRoute
  '/_dashboard/manager/team/$staffId': typeof DashboardManagerTeamStaffIdRoute
  '/_dashboard/admin/admins/': typeof DashboardAdminAdminsIndexRoute
  '/_dashboard/admin/audit/': typeof DashboardAdminAuditIndexRoute
  '/_dashboard/admin/locations/': typeof DashboardAdminLocationsIndexRoute
  '/_dashboard/admin/managers/': typeof DashboardAdminManagersIndexRoute
  '/_dashboard/admin/schedules/': typeof DashboardAdminSchedulesIndexRoute
  '/_dashboard/admin/staff/': typeof DashboardAdminStaffIndexRoute
  '/_dashboard/manager/locations/': typeof DashboardManagerLocationsIndexRoute
  '/_dashboard/manager/requests/': typeof DashboardManagerRequestsIndexRoute
  '/_dashboard/manager/schedule/': typeof DashboardManagerScheduleIndexRoute
  '/_dashboard/manager/team/': typeof DashboardManagerTeamIndexRoute
  '/_dashboard/staff/coverage/': typeof DashboardStaffCoverageIndexRoute
  '/_dashboard/staff/notifications/': typeof DashboardStaffNotificationsIndexRoute
  '/_dashboard/manager/schedule/$locationId/$weekStart': typeof DashboardManagerScheduleLocationIdWeekStartRoute
  '/_dashboard/manager/schedule/$locationId/': typeof DashboardManagerScheduleLocationIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/icon'
    | '/privacy'
    | '/terms'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/auth/'
    | '/admin/schedules'
    | '/api/auth/$'
    | '/admin/'
    | '/manager/'
    | '/staff/'
    | '/admin/managers/$managerId'
    | '/admin/schedules/on-duty'
    | '/admin/schedules/who'
    | '/admin/staff/$staffId'
    | '/manager/team/$staffId'
    | '/admin/admins/'
    | '/admin/audit/'
    | '/admin/locations/'
    | '/admin/managers/'
    | '/admin/schedules/'
    | '/admin/staff/'
    | '/manager/locations/'
    | '/manager/requests/'
    | '/manager/schedule/'
    | '/manager/team/'
    | '/staff/coverage/'
    | '/staff/notifications/'
    | '/manager/schedule/$locationId/$weekStart'
    | '/manager/schedule/$locationId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/icon'
    | '/privacy'
    | '/terms'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/auth'
    | '/api/auth/$'
    | '/admin'
    | '/manager'
    | '/staff'
    | '/admin/managers/$managerId'
    | '/admin/schedules/on-duty'
    | '/admin/schedules/who'
    | '/admin/staff/$staffId'
    | '/manager/team/$staffId'
    | '/admin/admins'
    | '/admin/audit'
    | '/admin/locations'
    | '/admin/managers'
    | '/admin/schedules'
    | '/admin/staff'
    | '/manager/locations'
    | '/manager/requests'
    | '/manager/schedule'
    | '/manager/team'
    | '/staff/coverage'
    | '/staff/notifications'
    | '/manager/schedule/$locationId/$weekStart'
    | '/manager/schedule/$locationId'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/auth'
    | '/icon'
    | '/privacy'
    | '/terms'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/auth/'
    | '/_dashboard/admin/schedules'
    | '/api/auth/$'
    | '/_dashboard/admin/'
    | '/_dashboard/manager/'
    | '/_dashboard/staff/'
    | '/_dashboard/admin/managers/$managerId'
    | '/_dashboard/admin/schedules/on-duty'
    | '/_dashboard/admin/schedules/who'
    | '/_dashboard/admin/staff/$staffId'
    | '/_dashboard/manager/team/$staffId'
    | '/_dashboard/admin/admins/'
    | '/_dashboard/admin/audit/'
    | '/_dashboard/admin/locations/'
    | '/_dashboard/admin/managers/'
    | '/_dashboard/admin/schedules/'
    | '/_dashboard/admin/staff/'
    | '/_dashboard/manager/locations/'
    | '/_dashboard/manager/requests/'
    | '/_dashboard/manager/schedule/'
    | '/_dashboard/manager/team/'
    | '/_dashboard/staff/coverage/'
    | '/_dashboard/staff/notifications/'
    | '/_dashboard/manager/schedule/$locationId/$weekStart'
    | '/_dashboard/manager/schedule/$locationId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  IconRoute: typeof IconRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/icon': {
      id: '/icon'
      path: '/icon'
      fullPath: '/icon'
      preLoaderRoute: typeof IconRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_dashboard/admin/': {
      id: '/_dashboard/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/admin/schedules': {
      id: '/_dashboard/admin/schedules'
      path: '/admin/schedules'
      fullPath: '/admin/schedules'
      preLoaderRoute: typeof DashboardAdminSchedulesRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/manager/': {
      id: '/_dashboard/manager/'
      path: '/manager'
      fullPath: '/manager/'
      preLoaderRoute: typeof DashboardManagerIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/staff/': {
      id: '/_dashboard/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof DashboardStaffIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/admin/admins/': {
      id: '/_dashboard/admin/admins/'
      path: '/admin/admins'
      fullPath: '/admin/admins/'
      preLoaderRoute: typeof DashboardAdminAdminsIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/admin/audit/': {
      id: '/_dashboard/admin/audit/'
      path: '/admin/audit'
      fullPath: '/admin/audit/'
      preLoaderRoute: typeof DashboardAdminAuditIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/admin/locations/': {
      id: '/_dashboard/admin/locations/'
      path: '/admin/locations'
      fullPath: '/admin/locations/'
      preLoaderRoute: typeof DashboardAdminLocationsIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/admin/managers/': {
      id: '/_dashboard/admin/managers/'
      path: '/admin/managers'
      fullPath: '/admin/managers/'
      preLoaderRoute: typeof DashboardAdminManagersIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/admin/managers/$managerId': {
      id: '/_dashboard/admin/managers/$managerId'
      path: '/admin/managers/$managerId'
      fullPath: '/admin/managers/$managerId'
      preLoaderRoute: typeof DashboardAdminManagersManagerIdRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/admin/schedules/': {
      id: '/_dashboard/admin/schedules/'
      path: '/'
      fullPath: '/admin/schedules/'
      preLoaderRoute: typeof DashboardAdminSchedulesIndexRouteImport
      parentRoute: typeof DashboardAdminSchedulesRoute
    }
    '/_dashboard/admin/schedules/on-duty': {
      id: '/_dashboard/admin/schedules/on-duty'
      path: '/on-duty'
      fullPath: '/admin/schedules/on-duty'
      preLoaderRoute: typeof DashboardAdminSchedulesOnDutyRouteImport
      parentRoute: typeof DashboardAdminSchedulesRoute
    }
    '/_dashboard/admin/schedules/who': {
      id: '/_dashboard/admin/schedules/who'
      path: '/who'
      fullPath: '/admin/schedules/who'
      preLoaderRoute: typeof DashboardAdminSchedulesWhoRouteImport
      parentRoute: typeof DashboardAdminSchedulesRoute
    }
    '/_dashboard/admin/staff/': {
      id: '/_dashboard/admin/staff/'
      path: '/admin/staff'
      fullPath: '/admin/staff/'
      preLoaderRoute: typeof DashboardAdminStaffIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/admin/staff/$staffId': {
      id: '/_dashboard/admin/staff/$staffId'
      path: '/admin/staff/$staffId'
      fullPath: '/admin/staff/$staffId'
      preLoaderRoute: typeof DashboardAdminStaffStaffIdRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/manager/locations/': {
      id: '/_dashboard/manager/locations/'
      path: '/manager/locations'
      fullPath: '/manager/locations/'
      preLoaderRoute: typeof DashboardManagerLocationsIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/manager/requests/': {
      id: '/_dashboard/manager/requests/'
      path: '/manager/requests'
      fullPath: '/manager/requests/'
      preLoaderRoute: typeof DashboardManagerRequestsIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/manager/schedule/': {
      id: '/_dashboard/manager/schedule/'
      path: '/manager/schedule'
      fullPath: '/manager/schedule/'
      preLoaderRoute: typeof DashboardManagerScheduleIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/manager/team/': {
      id: '/_dashboard/manager/team/'
      path: '/manager/team'
      fullPath: '/manager/team/'
      preLoaderRoute: typeof DashboardManagerTeamIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/manager/team/$staffId': {
      id: '/_dashboard/manager/team/$staffId'
      path: '/manager/team/$staffId'
      fullPath: '/manager/team/$staffId'
      preLoaderRoute: typeof DashboardManagerTeamStaffIdRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/staff/coverage/': {
      id: '/_dashboard/staff/coverage/'
      path: '/staff/coverage'
      fullPath: '/staff/coverage/'
      preLoaderRoute: typeof DashboardStaffCoverageIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/staff/notifications/': {
      id: '/_dashboard/staff/notifications/'
      path: '/staff/notifications'
      fullPath: '/staff/notifications/'
      preLoaderRoute: typeof DashboardStaffNotificationsIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/manager/schedule/$locationId/': {
      id: '/_dashboard/manager/schedule/$locationId/'
      path: '/manager/schedule/$locationId'
      fullPath: '/manager/schedule/$locationId/'
      preLoaderRoute: typeof DashboardManagerScheduleLocationIdIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/manager/schedule/$locationId/$weekStart': {
      id: '/_dashboard/manager/schedule/$locationId/$weekStart'
      path: '/manager/schedule/$locationId/$weekStart'
      fullPath: '/manager/schedule/$locationId/$weekStart'
      preLoaderRoute: typeof DashboardManagerScheduleLocationIdWeekStartRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
  }
}

interface DashboardAdminSchedulesRouteChildren {
  DashboardAdminSchedulesOnDutyRoute: typeof DashboardAdminSchedulesOnDutyRoute
  DashboardAdminSchedulesWhoRoute: typeof DashboardAdminSchedulesWhoRoute
  DashboardAdminSchedulesIndexRoute: typeof DashboardAdminSchedulesIndexRoute
}

const DashboardAdminSchedulesRouteChildren: DashboardAdminSchedulesRouteChildren =
  {
    DashboardAdminSchedulesOnDutyRoute: DashboardAdminSchedulesOnDutyRoute,
    DashboardAdminSchedulesWhoRoute: DashboardAdminSchedulesWhoRoute,
    DashboardAdminSchedulesIndexRoute: DashboardAdminSchedulesIndexRoute,
  }

const DashboardAdminSchedulesRouteWithChildren =
  DashboardAdminSchedulesRoute._addFileChildren(
    DashboardAdminSchedulesRouteChildren,
  )

interface DashboardLayoutRouteChildren {
  DashboardAdminSchedulesRoute: typeof DashboardAdminSchedulesRouteWithChildren
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
  DashboardManagerIndexRoute: typeof DashboardManagerIndexRoute
  DashboardStaffIndexRoute: typeof DashboardStaffIndexRoute
  DashboardAdminManagersManagerIdRoute: typeof DashboardAdminManagersManagerIdRoute
  DashboardAdminStaffStaffIdRoute: typeof DashboardAdminStaffStaffIdRoute
  DashboardManagerTeamStaffIdRoute: typeof DashboardManagerTeamStaffIdRoute
  DashboardAdminAdminsIndexRoute: typeof DashboardAdminAdminsIndexRoute
  DashboardAdminAuditIndexRoute: typeof DashboardAdminAuditIndexRoute
  DashboardAdminLocationsIndexRoute: typeof DashboardAdminLocationsIndexRoute
  DashboardAdminManagersIndexRoute: typeof DashboardAdminManagersIndexRoute
  DashboardAdminStaffIndexRoute: typeof DashboardAdminStaffIndexRoute
  DashboardManagerLocationsIndexRoute: typeof DashboardManagerLocationsIndexRoute
  DashboardManagerRequestsIndexRoute: typeof DashboardManagerRequestsIndexRoute
  DashboardManagerScheduleIndexRoute: typeof DashboardManagerScheduleIndexRoute
  DashboardManagerTeamIndexRoute: typeof DashboardManagerTeamIndexRoute
  DashboardStaffCoverageIndexRoute: typeof DashboardStaffCoverageIndexRoute
  DashboardStaffNotificationsIndexRoute: typeof DashboardStaffNotificationsIndexRoute
  DashboardManagerScheduleLocationIdWeekStartRoute: typeof DashboardManagerScheduleLocationIdWeekStartRoute
  DashboardManagerScheduleLocationIdIndexRoute: typeof DashboardManagerScheduleLocationIdIndexRoute
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardAdminSchedulesRoute: DashboardAdminSchedulesRouteWithChildren,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
  DashboardManagerIndexRoute: DashboardManagerIndexRoute,
  DashboardStaffIndexRoute: DashboardStaffIndexRoute,
  DashboardAdminManagersManagerIdRoute: DashboardAdminManagersManagerIdRoute,
  DashboardAdminStaffStaffIdRoute: DashboardAdminStaffStaffIdRoute,
  DashboardManagerTeamStaffIdRoute: DashboardManagerTeamStaffIdRoute,
  DashboardAdminAdminsIndexRoute: DashboardAdminAdminsIndexRoute,
  DashboardAdminAuditIndexRoute: DashboardAdminAuditIndexRoute,
  DashboardAdminLocationsIndexRoute: DashboardAdminLocationsIndexRoute,
  DashboardAdminManagersIndexRoute: DashboardAdminManagersIndexRoute,
  DashboardAdminStaffIndexRoute: DashboardAdminStaffIndexRoute,
  DashboardManagerLocationsIndexRoute: DashboardManagerLocationsIndexRoute,
  DashboardManagerRequestsIndexRoute: DashboardManagerRequestsIndexRoute,
  DashboardManagerScheduleIndexRoute: DashboardManagerScheduleIndexRoute,
  DashboardManagerTeamIndexRoute: DashboardManagerTeamIndexRoute,
  DashboardStaffCoverageIndexRoute: DashboardStaffCoverageIndexRoute,
  DashboardStaffNotificationsIndexRoute: DashboardStaffNotificationsIndexRoute,
  DashboardManagerScheduleLocationIdWeekStartRoute:
    DashboardManagerScheduleLocationIdWeekStartRoute,
  DashboardManagerScheduleLocationIdIndexRoute:
    DashboardManagerScheduleLocationIdIndexRoute,
}

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
)

interface AuthLayoutRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  IconRoute: IconRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
