/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardLayoutRouteImport } from './routes/_dashboard/layout'
import { Route as AuthLayoutRouteImport } from './routes/auth/layout'
import { Route as IconRouteImport } from './routes/icon'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as DashboardAdminRouteImport } from './routes/_dashboard/admin'
import { Route as DashboardManagerRouteImport } from './routes/_dashboard/manager'
import { Route as DashboardStaffRouteImport } from './routes/_dashboard/staff'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as DashboardAdminIndexRouteImport } from './routes/_dashboard/admin/index'
import { Route as DashboardManagerIndexRouteImport } from './routes/_dashboard/manager/index'
import { Route as DashboardStaffIndexRouteImport } from './routes/_dashboard/staff/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardAdminLocationsIndexRouteImport } from './routes/_dashboard/admin/locations/index'
import { Route as DashboardAdminManagersIndexRouteImport } from './routes/_dashboard/admin/managers/index'
import { Route as DashboardAdminScheduleIndexRouteImport } from './routes/_dashboard/admin/schedule/index'
import { Route as DashboardAdminUsersIndexRouteImport } from './routes/_dashboard/admin/users/index'
import { Route as DashboardManagerLocationsIndexRouteImport } from './routes/_dashboard/manager/locations/index'
import { Route as DashboardManagerScheduleIndexRouteImport } from './routes/_dashboard/manager/schedule/index'
import { Route as DashboardManagerTeamIndexRouteImport } from './routes/_dashboard/manager/team/index'
import { Route as DashboardStaffAvailabilityIndexRouteImport } from './routes/_dashboard/staff/availability/index'
import { Route as DashboardAdminManagersUserIdIndexRouteImport } from './routes/_dashboard/admin/managers/$userId/index'
import { Route as DashboardAdminUsersUserIdIndexRouteImport } from './routes/_dashboard/admin/users/$userId/index'
import { Route as DashboardManagerTeamUserIdIndexRouteImport } from './routes/_dashboard/manager/team/$userId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IconRoute = IconRouteImport.update({
  id: '/icon',
  path: '/icon',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardManagerRoute = DashboardManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardStaffRoute = DashboardStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardManagerIndexRoute = DashboardManagerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardManagerRoute,
} as any)
const DashboardStaffIndexRoute = DashboardStaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardStaffRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminLocationsIndexRoute =
  DashboardAdminLocationsIndexRouteImport.update({
    id: '/locations/',
    path: '/locations/',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminManagersIndexRoute =
  DashboardAdminManagersIndexRouteImport.update({
    id: '/managers/',
    path: '/managers/',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminScheduleIndexRoute =
  DashboardAdminScheduleIndexRouteImport.update({
    id: '/schedule/',
    path: '/schedule/',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminUsersIndexRoute =
  DashboardAdminUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardManagerLocationsIndexRoute =
  DashboardManagerLocationsIndexRouteImport.update({
    id: '/locations/',
    path: '/locations/',
    getParentRoute: () => DashboardManagerRoute,
  } as any)
const DashboardManagerScheduleIndexRoute =
  DashboardManagerScheduleIndexRouteImport.update({
    id: '/schedule/',
    path: '/schedule/',
    getParentRoute: () => DashboardManagerRoute,
  } as any)
const DashboardManagerTeamIndexRoute =
  DashboardManagerTeamIndexRouteImport.update({
    id: '/team/',
    path: '/team/',
    getParentRoute: () => DashboardManagerRoute,
  } as any)
const DashboardStaffAvailabilityIndexRoute =
  DashboardStaffAvailabilityIndexRouteImport.update({
    id: '/availability/',
    path: '/availability/',
    getParentRoute: () => DashboardStaffRoute,
  } as any)
const DashboardAdminManagersUserIdIndexRoute =
  DashboardAdminManagersUserIdIndexRouteImport.update({
    id: '/managers/$userId/',
    path: '/managers/$userId/',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminUsersUserIdIndexRoute =
  DashboardAdminUsersUserIdIndexRouteImport.update({
    id: '/users/$userId/',
    path: '/users/$userId/',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardManagerTeamUserIdIndexRoute =
  DashboardManagerTeamUserIdIndexRouteImport.update({
    id: '/team/$userId/',
    path: '/team/$userId/',
    getParentRoute: () => DashboardManagerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthLayoutRouteWithChildren
  '/icon': typeof IconRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin': typeof DashboardAdminRouteWithChildren
  '/manager': typeof DashboardManagerRouteWithChildren
  '/staff': typeof DashboardStaffRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/': typeof AuthIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/': typeof DashboardAdminIndexRoute
  '/manager/': typeof DashboardManagerIndexRoute
  '/staff/': typeof DashboardStaffIndexRoute
  '/admin/locations/': typeof DashboardAdminLocationsIndexRoute
  '/admin/managers/': typeof DashboardAdminManagersIndexRoute
  '/admin/schedule/': typeof DashboardAdminScheduleIndexRoute
  '/admin/users/': typeof DashboardAdminUsersIndexRoute
  '/manager/locations/': typeof DashboardManagerLocationsIndexRoute
  '/manager/schedule/': typeof DashboardManagerScheduleIndexRoute
  '/manager/team/': typeof DashboardManagerTeamIndexRoute
  '/staff/availability/': typeof DashboardStaffAvailabilityIndexRoute
  '/admin/managers/$userId/': typeof DashboardAdminManagersUserIdIndexRoute
  '/admin/users/$userId/': typeof DashboardAdminUsersUserIdIndexRoute
  '/manager/team/$userId/': typeof DashboardManagerTeamUserIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/icon': typeof IconRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth': typeof AuthIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin': typeof DashboardAdminIndexRoute
  '/manager': typeof DashboardManagerIndexRoute
  '/staff': typeof DashboardStaffIndexRoute
  '/admin/locations': typeof DashboardAdminLocationsIndexRoute
  '/admin/managers': typeof DashboardAdminManagersIndexRoute
  '/admin/schedule': typeof DashboardAdminScheduleIndexRoute
  '/admin/users': typeof DashboardAdminUsersIndexRoute
  '/manager/locations': typeof DashboardManagerLocationsIndexRoute
  '/manager/schedule': typeof DashboardManagerScheduleIndexRoute
  '/manager/team': typeof DashboardManagerTeamIndexRoute
  '/staff/availability': typeof DashboardStaffAvailabilityIndexRoute
  '/admin/managers/$userId': typeof DashboardAdminManagersUserIdIndexRoute
  '/admin/users/$userId': typeof DashboardAdminUsersUserIdIndexRoute
  '/manager/team/$userId': typeof DashboardManagerTeamUserIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardLayoutRouteWithChildren
  '/auth': typeof AuthLayoutRouteWithChildren
  '/icon': typeof IconRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/_dashboard/manager': typeof DashboardManagerRouteWithChildren
  '/_dashboard/staff': typeof DashboardStaffRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/': typeof AuthIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_dashboard/admin/': typeof DashboardAdminIndexRoute
  '/_dashboard/manager/': typeof DashboardManagerIndexRoute
  '/_dashboard/staff/': typeof DashboardStaffIndexRoute
  '/_dashboard/admin/locations/': typeof DashboardAdminLocationsIndexRoute
  '/_dashboard/admin/managers/': typeof DashboardAdminManagersIndexRoute
  '/_dashboard/admin/schedule/': typeof DashboardAdminScheduleIndexRoute
  '/_dashboard/admin/users/': typeof DashboardAdminUsersIndexRoute
  '/_dashboard/manager/locations/': typeof DashboardManagerLocationsIndexRoute
  '/_dashboard/manager/schedule/': typeof DashboardManagerScheduleIndexRoute
  '/_dashboard/manager/team/': typeof DashboardManagerTeamIndexRoute
  '/_dashboard/staff/availability/': typeof DashboardStaffAvailabilityIndexRoute
  '/_dashboard/admin/managers/$userId/': typeof DashboardAdminManagersUserIdIndexRoute
  '/_dashboard/admin/users/$userId/': typeof DashboardAdminUsersUserIdIndexRoute
  '/_dashboard/manager/team/$userId/': typeof DashboardManagerTeamUserIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/icon'
    | '/privacy'
    | '/terms'
    | '/admin'
    | '/manager'
    | '/staff'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/auth/'
    | '/api/auth/$'
    | '/admin/'
    | '/manager/'
    | '/staff/'
    | '/admin/locations/'
    | '/admin/managers/'
    | '/admin/schedule/'
    | '/admin/users/'
    | '/manager/locations/'
    | '/manager/schedule/'
    | '/manager/team/'
    | '/staff/availability/'
    | '/admin/managers/$userId/'
    | '/admin/users/$userId/'
    | '/manager/team/$userId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/icon'
    | '/privacy'
    | '/terms'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/auth'
    | '/api/auth/$'
    | '/admin'
    | '/manager'
    | '/staff'
    | '/admin/locations'
    | '/admin/managers'
    | '/admin/schedule'
    | '/admin/users'
    | '/manager/locations'
    | '/manager/schedule'
    | '/manager/team'
    | '/staff/availability'
    | '/admin/managers/$userId'
    | '/admin/users/$userId'
    | '/manager/team/$userId'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/auth'
    | '/icon'
    | '/privacy'
    | '/terms'
    | '/_dashboard/admin'
    | '/_dashboard/manager'
    | '/_dashboard/staff'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/auth/'
    | '/api/auth/$'
    | '/_dashboard/admin/'
    | '/_dashboard/manager/'
    | '/_dashboard/staff/'
    | '/_dashboard/admin/locations/'
    | '/_dashboard/admin/managers/'
    | '/_dashboard/admin/schedule/'
    | '/_dashboard/admin/users/'
    | '/_dashboard/manager/locations/'
    | '/_dashboard/manager/schedule/'
    | '/_dashboard/manager/team/'
    | '/_dashboard/staff/availability/'
    | '/_dashboard/admin/managers/$userId/'
    | '/_dashboard/admin/users/$userId/'
    | '/_dashboard/manager/team/$userId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  IconRoute: typeof IconRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/icon': {
      id: '/icon'
      path: '/icon'
      fullPath: '/icon'
      preLoaderRoute: typeof IconRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/admin': {
      id: '/_dashboard/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/manager': {
      id: '/_dashboard/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof DashboardManagerRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/staff': {
      id: '/_dashboard/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof DashboardStaffRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_dashboard/admin/': {
      id: '/_dashboard/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/_dashboard/manager/': {
      id: '/_dashboard/manager/'
      path: '/'
      fullPath: '/manager/'
      preLoaderRoute: typeof DashboardManagerIndexRouteImport
      parentRoute: typeof DashboardManagerRoute
    }
    '/_dashboard/staff/': {
      id: '/_dashboard/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof DashboardStaffIndexRouteImport
      parentRoute: typeof DashboardStaffRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/admin/locations/': {
      id: '/_dashboard/admin/locations/'
      path: '/locations'
      fullPath: '/admin/locations/'
      preLoaderRoute: typeof DashboardAdminLocationsIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/_dashboard/admin/managers/': {
      id: '/_dashboard/admin/managers/'
      path: '/managers'
      fullPath: '/admin/managers/'
      preLoaderRoute: typeof DashboardAdminManagersIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/_dashboard/admin/schedule/': {
      id: '/_dashboard/admin/schedule/'
      path: '/schedule'
      fullPath: '/admin/schedule/'
      preLoaderRoute: typeof DashboardAdminScheduleIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/_dashboard/admin/users/': {
      id: '/_dashboard/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof DashboardAdminUsersIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/_dashboard/manager/locations/': {
      id: '/_dashboard/manager/locations/'
      path: '/locations'
      fullPath: '/manager/locations/'
      preLoaderRoute: typeof DashboardManagerLocationsIndexRouteImport
      parentRoute: typeof DashboardManagerRoute
    }
    '/_dashboard/manager/schedule/': {
      id: '/_dashboard/manager/schedule/'
      path: '/schedule'
      fullPath: '/manager/schedule/'
      preLoaderRoute: typeof DashboardManagerScheduleIndexRouteImport
      parentRoute: typeof DashboardManagerRoute
    }
    '/_dashboard/manager/team/': {
      id: '/_dashboard/manager/team/'
      path: '/team'
      fullPath: '/manager/team/'
      preLoaderRoute: typeof DashboardManagerTeamIndexRouteImport
      parentRoute: typeof DashboardManagerRoute
    }
    '/_dashboard/staff/availability/': {
      id: '/_dashboard/staff/availability/'
      path: '/availability'
      fullPath: '/staff/availability/'
      preLoaderRoute: typeof DashboardStaffAvailabilityIndexRouteImport
      parentRoute: typeof DashboardStaffRoute
    }
    '/_dashboard/admin/managers/$userId/': {
      id: '/_dashboard/admin/managers/$userId/'
      path: '/managers/$userId'
      fullPath: '/admin/managers/$userId/'
      preLoaderRoute: typeof DashboardAdminManagersUserIdIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/_dashboard/admin/users/$userId/': {
      id: '/_dashboard/admin/users/$userId/'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId/'
      preLoaderRoute: typeof DashboardAdminUsersUserIdIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/_dashboard/manager/team/$userId/': {
      id: '/_dashboard/manager/team/$userId/'
      path: '/team/$userId'
      fullPath: '/manager/team/$userId/'
      preLoaderRoute: typeof DashboardManagerTeamUserIdIndexRouteImport
      parentRoute: typeof DashboardManagerRoute
    }
  }
}

interface DashboardAdminRouteChildren {
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
  DashboardAdminLocationsIndexRoute: typeof DashboardAdminLocationsIndexRoute
  DashboardAdminManagersIndexRoute: typeof DashboardAdminManagersIndexRoute
  DashboardAdminScheduleIndexRoute: typeof DashboardAdminScheduleIndexRoute
  DashboardAdminUsersIndexRoute: typeof DashboardAdminUsersIndexRoute
  DashboardAdminManagersUserIdIndexRoute: typeof DashboardAdminManagersUserIdIndexRoute
  DashboardAdminUsersUserIdIndexRoute: typeof DashboardAdminUsersUserIdIndexRoute
}

const DashboardAdminRouteChildren: DashboardAdminRouteChildren = {
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
  DashboardAdminLocationsIndexRoute: DashboardAdminLocationsIndexRoute,
  DashboardAdminManagersIndexRoute: DashboardAdminManagersIndexRoute,
  DashboardAdminScheduleIndexRoute: DashboardAdminScheduleIndexRoute,
  DashboardAdminUsersIndexRoute: DashboardAdminUsersIndexRoute,
  DashboardAdminManagersUserIdIndexRoute:
    DashboardAdminManagersUserIdIndexRoute,
  DashboardAdminUsersUserIdIndexRoute: DashboardAdminUsersUserIdIndexRoute,
}

const DashboardAdminRouteWithChildren = DashboardAdminRoute._addFileChildren(
  DashboardAdminRouteChildren,
)

interface DashboardManagerRouteChildren {
  DashboardManagerIndexRoute: typeof DashboardManagerIndexRoute
  DashboardManagerLocationsIndexRoute: typeof DashboardManagerLocationsIndexRoute
  DashboardManagerScheduleIndexRoute: typeof DashboardManagerScheduleIndexRoute
  DashboardManagerTeamIndexRoute: typeof DashboardManagerTeamIndexRoute
  DashboardManagerTeamUserIdIndexRoute: typeof DashboardManagerTeamUserIdIndexRoute
}

const DashboardManagerRouteChildren: DashboardManagerRouteChildren = {
  DashboardManagerIndexRoute: DashboardManagerIndexRoute,
  DashboardManagerLocationsIndexRoute: DashboardManagerLocationsIndexRoute,
  DashboardManagerScheduleIndexRoute: DashboardManagerScheduleIndexRoute,
  DashboardManagerTeamIndexRoute: DashboardManagerTeamIndexRoute,
  DashboardManagerTeamUserIdIndexRoute: DashboardManagerTeamUserIdIndexRoute,
}

const DashboardManagerRouteWithChildren =
  DashboardManagerRoute._addFileChildren(DashboardManagerRouteChildren)

interface DashboardStaffRouteChildren {
  DashboardStaffIndexRoute: typeof DashboardStaffIndexRoute
  DashboardStaffAvailabilityIndexRoute: typeof DashboardStaffAvailabilityIndexRoute
}

const DashboardStaffRouteChildren: DashboardStaffRouteChildren = {
  DashboardStaffIndexRoute: DashboardStaffIndexRoute,
  DashboardStaffAvailabilityIndexRoute: DashboardStaffAvailabilityIndexRoute,
}

const DashboardStaffRouteWithChildren = DashboardStaffRoute._addFileChildren(
  DashboardStaffRouteChildren,
)

interface DashboardLayoutRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRouteWithChildren
  DashboardManagerRoute: typeof DashboardManagerRouteWithChildren
  DashboardStaffRoute: typeof DashboardStaffRouteWithChildren
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardAdminRoute: DashboardAdminRouteWithChildren,
  DashboardManagerRoute: DashboardManagerRouteWithChildren,
  DashboardStaffRoute: DashboardStaffRouteWithChildren,
}

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
)

interface AuthLayoutRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  IconRoute: IconRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
